theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true
shell = ["zsh", "-c"]
end-of-line-diagnostics = "hint"
scroll-lines = 1
jump-label-alphabet = "fjdkslrueiwovmc,x."

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "diagnostics"]
right = ["workspace-diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false

[editor.lsp]
goto-reference-include-declaration = false

[keys.normal.space]
space = "file_picker"
":" = "command_palette"
o = "@:o <C-r>%<C-w>"

[keys.normal."+".g]
b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
o = ":echo %sh{git blame --porcelain -L %{cursor_line},+1 %{buffer_name} | head -1 | cut -d' ' -f1 | xargs gh browse}"

[keys.normal]
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-j = ":bc"
A-k = ":new"
C-d = ["page_cursor_half_down", "align_view_center"]
C-u = ["page_cursor_half_up", "align_view_center"]

[keys.insert]
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-j = ":bc"
A-k = ":new"

[keys.select]
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-j = ":bc"
A-k = ":new"

