theme = "gruvbox-material-dark-transparent"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true
shell = ["nu", "-c"]
end-of-line-diagnostics = "hint"
jump-label-alphabet = "fjdkslrueiwovm"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "diagnostics"]
right = ["workspace-diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = true
git-ignore = true
git-global = true

[editor.lsp]
goto-reference-include-declaration = false

[keys.normal.space]
space = "file_picker"
":" = "command_palette"
o = "@:o <C-r>%<C-w>"

[keys.normal."+".g]
b = ":echo %sh{git-blame-info.nu %{buffer_name} %{cursor_line}}"
o = ":echo %sh{git blame --porcelain -L %{cursor_line},+1 %{buffer_name} | head -1 | cut -d' ' -f1 | xargs gh browse}"

[keys.normal]
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-j = ":bc"
A-k = ":new"
pageup = ["page_cursor_half_up", "align_view_center"]
pagedown = ["page_cursor_half_down", "align_view_center"]
C-d = "@16jzc"
C-u = "@16kzc"
n = ["search_next", "align_view_center"]
N = ["search_prev", "align_view_center"]
# C-ret = [":write", ":sh wchat chat %{buffer_name}"]
# C-ret = [":write", ":sh cat %{buffer_name} | mdc chat --stream >> %{buffer_name}"]

[keys.insert]
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-j = ":bc"
A-k = ":new"
C-c = "toggle_comments"
# C-ret = ["normal_mode", ":write", ":sh wchat chat %{buffer_name}"]
C-ret = ["normal_mode", ":write", ":sh cat %{buffer_name} | mdc chat --stream >> %{buffer_name}"]

[keys.select]
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-j = ":bc"
A-k = ":new"

