theme = "gruvbox"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-j = ":bc"
A-k = ":new"

[keys.insert]
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-j = ":bc"
A-k = ":new"

