[[language]]
name = "php"
auto-format = true
# formatter = { command = "hxpint.sh", args = ["--stdin"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name= "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "javascript"
# formatter = { command = 'prettier', args = ["--parser", "typescript"] }
# language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
auto-format = false
# indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
auto-format = true
indent = { tab-width = 4, unit = "    " }
comment-token = "//"
block-comment-tokens = { start = "{/*", end = "*/}" }

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
auto-format = true
indent = { tab-width = 4, unit = "    " }
comment-token = "//"
block-comment-tokens = { start = "{/*", end = "*/}" }

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
