format = """
$username\
[|](dimmed) $directory\
[|](dimmed) $git_branch\
[|](dimmed) $time\n
"""

palette = 'gruvbox-material'

[palettes.rose-pine-moon]
text0 = '#9ccfd8'
text1 = '#c4a7e7'
text2 = '#ebbcba'
text3 = '#eb6f92'

[palettes.catppuccin-mocha]
text0 = '#cba6f7'
text1 = '#b4befe'
text2 = '#f5c2e7'
text3 = '#f2cdcd'

[palettes.gruvbox-light]
text0 = '#79740e'
text1 = '#427b58'
text2 = '#076678'
text3 = '#9d0006'

[palettes.gruvbox-material]
text0 = '#b8bb26'
text1 = '#8ec07c'
text2 = '#83a598'
text3 = '#fe8019'

[username]
format = "[$user]($style) "
show_always = true
style_user = "fg:text0 bold"
style_root = "fg:text3 bold"

[directory]
format = "[$path]($style) "
style = "fg:text1"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "
style = "fg:text2"
symbol = " "

[time]
disabled = false
format = "[$time]($style)"
style = "fg:text3"
time_format = "%I:%M%P"
